[0m23:39:52.806925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6BDB3A790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6BDBF8F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6BDBFB4D0>]}


============================== 23:39:52.828927 | bda1ace5-0282-411f-a896-2205978e09bc ==============================
[0m23:39:52.828927 [info ] [MainThread]: Running with dbt=1.10.6
[0m23:39:52.828927 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nlhtung\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt_project', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:39:52.848931 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\nlhtung\.dbt
[0m23:39:52.850946 [debug] [MainThread]: Starter project path: C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m23:39:52.916795 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:39:52.916795 [info ] [MainThread]: Setting up your profile.
[0m23:39:56.944059 [error] [MainThread]: Encountered an error:

[0m23:39:56.950990 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 128, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m23:39:56.950990 [debug] [MainThread]: Command `dbt init` failed at 23:39:56.950990 after 4.22 seconds
[0m23:39:56.957253 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6B5F0BF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6BDBFBA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A6BDBFB010>]}
[0m23:39:56.957253 [debug] [MainThread]: Flushing usage events
[0m23:39:58.313692 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:41:43.160721 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A24606F110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2460A2610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A2460A3410>]}


============================== 23:41:43.160721 | ce0776fd-0df2-42f5-a171-0238e4ab4e8c ==============================
[0m23:41:43.160721 [info ] [MainThread]: Running with dbt=1.10.6
[0m23:41:43.164855 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\nlhtung\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m23:41:43.183716 [info ] [MainThread]: A project called dbt_project already exists here.
[0m23:41:43.183716 [debug] [MainThread]: Command `dbt init` succeeded at 23:41:43.183716 after 0.09 seconds
[0m23:41:43.183716 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A23F48BF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A23F6DE350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A24606BE50>]}
[0m23:41:43.183716 [debug] [MainThread]: Flushing usage events
[0m23:41:44.546837 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:41:58.720173 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015B5DD7D010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015B5DCC1090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015B5CA6DD50>]}


============================== 23:41:58.727584 | f32235ca-3686-4f22-b425-632d24798d2d ==============================
[0m23:41:58.727584 [info ] [MainThread]: Running with dbt=1.10.6
[0m23:41:58.727584 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\nlhtung\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init dbt_project', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:41:58.737811 [debug] [MainThread]: Starter project path: C:\Users\nlhtung\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m23:41:58.768843 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:41:58.768843 [info ] [MainThread]: Setting up your profile.
[0m23:42:04.979362 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m23:42:04.979362 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m23:42:04.979362 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m23:42:35.589767 [info ] [MainThread]: Profile dbt_project written to C:\Users\nlhtung\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:42:35.593838 [debug] [MainThread]: Command `dbt init` succeeded at 23:42:35.593838 after 36.93 seconds
[0m23:42:35.593838 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015B570FBF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015B5DB41B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015B57109A90>]}
[0m23:42:35.596381 [debug] [MainThread]: Flushing usage events
[0m23:42:36.593891 [debug] [MainThread]: An error was encountered while trying to flush usage events
